Version 2.0

---
Children:
- Children:
  - Children:
    - Children: []
      Properties:
        Output Channel (PWM): !!robotbuilder.data.properties.ChoicesProperty
          choices: &id001 ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10',
            '11', '12', '13', '14', '15', '16', '17', '18', '19']
          default: '0'
          name: Output Channel (PWM)
          validators: &id002 [PWMOutput]
          value: '0'
      Base: Servo
      Name: Servo Pan
    - Children: []
      Properties:
        Output Channel (PWM): !!robotbuilder.data.properties.ChoicesProperty
          choices: *id001
          default: '0'
          name: Output Channel (PWM)
          validators: *id002
          value: '1'
      Base: Servo
      Name: Servo 2
    Properties:
      Default command parameters: !!robotbuilder.data.properties.ParametersProperty
        default: []
        name: Default command parameters
        validators: null
        value: []
      Default Command: !!robotbuilder.data.properties.TypeSelectionProperty {default: None,
        name: Default Command, type: Command, validators: null, value: Autonomous Command}
      Constants: !!robotbuilder.data.properties.ConstantsProperty
        default: []
        name: Constants
        validators: null
        value: []
    Base: Subsystem
    Name: Drive
  Properties: {}
  Base: Subsystems
  Name: Subsystems
- Children: []
  Properties: {}
  Base: OI
  Name: Operator Interface
- Children:
  - Children: []
    Properties:
      Parameters: !!robotbuilder.data.properties.ParametersProperty
        default: []
        name: Parameters
        validators: null
        value: []
      Requires: !!robotbuilder.data.properties.TypeSelectionProperty {default: None,
        name: Requires, type: Subsystem, validators: null, value: None}
      Parameter presets: !!robotbuilder.data.properties.ParameterSetProperty
        default: []
        name: Parameter presets
        validators: null
        value: []
      Button on SmartDashboard: !!robotbuilder.data.properties.BooleanProperty {default: true,
        name: Button on SmartDashboard, validators: null, value: true}
    Base: Command
    Name: Autonomous Command
  Properties: {}
  Base: Commands
  Name: Commands
Properties:
  Eclipse Workspace: !!robotbuilder.data.properties.FileProperty {default: 'C:\Users\bugey\workspace',
    extension: null, folder: true, name: Eclipse Workspace, validators: null, value: 'C:\Users\bugey\workspace'}
  Export Commands: !!robotbuilder.data.properties.BooleanProperty {default: true,
    name: Export Commands, validators: null, value: true}
  Autonomous command parameters: !!robotbuilder.data.properties.ParametersProperty
    default: []
    name: Autonomous command parameters
    validators: null
    value: []
  Java Package: !!robotbuilder.data.properties.StringProperty {default: org.usfirst.frc0000,
    name: Java Package, validators: null, value: org.usfirst.frc1073}
  Use Default Java Package: !!robotbuilder.data.properties.BooleanProperty {default: true,
    name: Use Default Java Package, validators: null, value: true}
  Team Number: !!robotbuilder.data.properties.IntegerProperty {default: 0, name: Team Number,
    validators: null, value: 1073}
  Export Subsystems: !!robotbuilder.data.properties.BooleanProperty {default: true,
    name: Export Subsystems, validators: null, value: true}
  Simulation World File: !!robotbuilder.data.properties.StringProperty {default: /usr/share/frcsim/worlds/GearsBotDemo.world,
    name: Simulation World File, validators: null, value: /usr/share/frcsim/worlds/GearsBotDemo.world}
  Wiring file location: !!robotbuilder.data.properties.FileProperty {default: 'C:\Users\bugey\',
    extension: null, folder: true, name: Wiring file location, validators: null, value: 'C:\Users\bugey\'}
  Autonomous Command: !!robotbuilder.data.properties.TypeSelectionProperty {default: None,
    name: Autonomous Command, type: Command, validators: null, value: Autonomous Command}
Base: Robot
Name: myTurret
